standalone_tags:
  [
    {id: 1, size: 0.065},
    {id: 2, size: 0.065},
    {id: 3, size: 0.065},
    {id: 4, size: 0.065},
    {id: 5, size: 0.065},
    {id: 20, size: 0.1},
    {id: 30, size: 0.07}
  ]
tag_bundles:
  [
  ]
